:toc:
:source-highlighter: coderay
= Icinga Plugin for Monitoring SAP/Sybase Database Server
John Knox <john@outlands.org.uk>
v1.0, 30/10/2018

== Introduction


== Database Server Monitoring

The plugin that runs most of the db checks is check_syb.ksh. The exit status
of the script defines the state of the monitoring component. Permitted exits
statuses are as follows

.Exit Statuses
[width="80%",options="header",cols="^,<"]
|===========================================================
|Exit Status|Description
|0    |Check has been passed successfully
|1    |The warning threshold has been exceeded by the script
|2    |The critical threshold has been exceeded by the check
|3    |An unknown status has been detected
|===========================================================


=== check_syb.ksh

This script runs a series of checks and handles the return status of a stored
procedure which performs the majority of the checks in the database server.
The one exception is the database space check which call the system procedure
sp_spaceused and processes it’s output. The script will be distributed with
the Icinga installation and placed in the plugins directory

------------------------------------------------------------
 check_syb.ksh <report id> <warn_at> <critical_at> [ <dbname> ]

 sp_dba_nagios [ null | 1-7 ] , @warn_at , @critical_at

 Parameter      Check                                Nos of params
 ---------      -----                                -------------
 null           This help message                                3
 1              ASE Uptime                                       3
 2              User Connections                                 3
 3              Blocking Connections                             3
 4              Transaction Log Used Percent                     4
 5              Database Used Percent(via shell script only)     4
 6              Replication Check                                4
 7              New Object Check                                 4
 8              Long Running Txn                                 3
 9              Appserver Connection Check                       3
 10             Phantom Lock Detection                           3
 11             Open Object Check                                3

 @warn_at       Warning Threshold
 @critical_at   Critical Threshold

 4th Parameter  Database Name, provided via check_syb.ksh script
                see - /usr/lib64/nagios/plugins/check_syb.ksh
------------------------------------------------------------

The script takes either three or four parameters

.Parameters
[width="80%",options="header",cols="1,1,4"]
|===========================================================
|Parameter Number|Parameter Name|Comments
|1    |Check ID | A numerical value or null between 1 and 9 identifying the
check to be performed

|2    |Warn at threshold | A numerical value that may be a hard limit or a percentage
depending on the check type that will trigger a warning
condition in Icinga

|3    |Critical at threshold | A numerical value that may be a hard limit or a percentage
depending on the check type that will trigger a critical
condition in Icinga

|4    |Database Name | A numerical value that may be a hard limit or a percentage
depending on the check type that will trigger a critical
condition in Icinga
|===========================================================


The script can be run on the command line for troubleshooting purposes, as
root on the monitored host

------------------------------------------------------------
cd /usr/lib64/nagios/plugins
[root@dlasedbagbl001 plugins]# sudo -u nagios ./check_syb.ksh 1 5 10
SYB Uptime : 5429 mins ok
------------------------------------------------------------

=== sp_dba_nagios

This stored procedure performs the checks within the database and formats the
message strings and return status required for Icinga. The stored procedure is
installed by the DBA Admin Package, and is run via the nagios database
account.

The stored procedure can be run on the SQL command line for troubleshooting purposes

------------------------------------------------------------
[sybase@dlasedbagbl001 sql]$ sql
1> sp_dba_nagios 3,10,20
2> go
SYB Blocked Processes : 0 - ok
(return status = 0)
------------------------------------------------------------
